# Site Settings
title: "Code Log Blog"
description: "Code Log Blog"

# Build Settings
# theme: jekyll-theme-minimal
remote_theme: abhinavs/moonwalk

# Plugins
plugins:
  - jekyll-feed
  - jekyll-remote-theme


